notifications:
  email: false

language: node_js

node_js:
  - 10

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci

before_script:
  - npm run lint
  - npm run build

script:
  - npm test

after_success:
  - npm test -- --coverage

after_script:
  - cat ./coverage/lcov.info | coveralls

deploy:
  provider: npm
  email: info@inveniosoftware.org
  api_key:
    secure: TQSwFR8jbDCXyTdFUWri6fV83XMoKSLlPo3FoXlW8rEPvVvUTfmmHG7+3jNaT21QIhzMo3Jpt57V+6igXVfxZUXZGoWcWKO6aphckIhucYbztQlHXhMC89oc+X/vscVykvaNoZ2hnxENCLtADH1t5FXsEdAmX9o+Vvyhs0MTGNyUaXAwsDNYwcZavU+0fw9kOWXtWBuUV7QfbO23/WTOd5YteASCCLjoV6Tv+ji+be812Q4LdQGr9ypoR837NozcjT7MTTd6GPl+w2Tn3GrQu8PuX+njogW9GZXR2+pve7l0LrZpUREJgvEpv9GpkETZJpYK4h3sTlO4tvt1hYnHd9UEhWhk72R0LkWh5DimQNlhU8HxPJuXaBhKfr3o2Uz0Nw7gCtRlVeictYmiaxfgTGr6muL8JNa0jyu77cneZJXC0mEpC5XwE2Og3T1MNVPaiEbTF1nbF5NN6lreqmwSaukzzbQHCqme2BiiJNcEMbBNXrmDKKJAdO8RVSvIJEpl8yUVSUd7wOAeJJhmw5/gMUunuijfCMJF/7OwTJ4b1pJb70B0rzLZkcqcK708C4DLPag/nnvp9OuqYhcNRMhUEAk/PTD5bvdjc5iMJ2LSUoV0GevVYhVZXxglRBn/GO75h4u4rUut28eQtu8ZwzpF9R0a5i3tBpfPRAOP/vVeDLo=
  on:
    branch: master
    tags: true
    repo: inveniosoftware/react-invenio-app-ils
