language: node_js

node_js:
  - 10

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci

before_script:
  - npm run lint
  - npm run build

script:
  - npm test

after_success:
  - npm test -- --coverage

after_script:
  - cat ./coverage/lcov.info | coveralls

before_deploy:
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: info@inveniosoftware.org
    on:
      branch: master
      tags: true
      repo: inveniosoftware/react-invenio-app-ils
